@startuml
class Hotel {
    +String nom
    +String adresse
    +Chambre[] chambres
    +Reservation[] reservations
    +consulterDispo(): Boolean
}

class Chambre {
    +String numero
    +Boolean dispo
    +reserver(): Boolean
}

class Reservation {
    +String date
    +Client client
    +Chambre chambre
}

class Client {
    +String nom
    +String email
    +reserverChambre(): Boolean
}

Hotel "1" -- "0..*" Chambre : contient
Chambre "0..*" -- "0..*" Reservation : réservée
Reservation "1" -- "1" Client : effectuée par

@enduml
